#!/bin/sh

now=$(( 3600*$(date +%H) + 60*$(date +%M) ))
strt=$(($now + 20))
endt=$(($now + 40))

boot1=$((7*3600 + 52*60))                                    # 07:52 reboot om 8 uur
boot2=$(($boot1 + 8*60))                                     # 08:00 nowstep = 8 min
boottime="[ \$now -eg $boot1 ] && [ \$now -lt $boot2 ]" 
# if eval $boottime; then reboot; fi                         # nb step is 9 min, checken?


while true; do

    now=$(( 3600*$(date +%H) + 60*$(date +%M) + $(date +%S) ))

    echo "1st" $strt $now $endt

    runtime="[ \$now -gt $strt ] && [ \$now -lt $endt ]"

    echo "2st" $strt $now $endt

    if eval $runtime; then

    echo "in the loop"

    fi

    echo "last" $strt $now $endt
    echo "sleeping 25 secs"
    sleep 25

done
